apiVersion: v1
kind: Service
metadata:
  name: crud-db-service
  namespace: crud-app

spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      protocol: TCP
      port: 5432
  selector:
      app: crud-db
      type: db
